import { useState } from 'react';
import GlassCard from '../../components/ui/GlassCard';
import GradientText from '../../components/ui/GradientText';
import Button from '../../components/ui/Button';

export default function Contact() {
  const [openFaq, setOpenFaq] = useState(0);

  const faqs = [
    {
      question: "What is the OakCred AI Score?",
      answer: "The OakCred AI Score is an alternative credit risk metric generated by our proprietary machine learning models. It analyzes thousands of non-traditional data points to provide a more accurate and inclusive assessment of borrower risk compared to legacy credit bureau scores."
    },
    {
      question: "How long does integration take?",
      answer: "You can start using the OakCred portal immediately without any technical integration. If you want to connect our assessment engine directly into your existing Loan Origination System (LOS), our well-documented API typically takes 1-2 weeks for a full integration."
    },
    {
      question: "Is borrower data secure and compliant?",
      answer: "Absolutely. We adhere to SOC 2 Type II standards and utilize bank-grade AES-256 encryption for all data at rest and in transit. We are fully compliant with major data privacy regulations."
    },
    {
      question: "Can I try the platform before committing?",
      answer: "Yes, we offer a 14-day free trial of our portal with full feature access and sample borrower data so you can test our risk models firsthand."
    }
  ];

  return (
    <div className="w-full">
      {/* ─── Hero Section ───────────────────────────── */}
      <section className="relative pt-40 pb-16 px-6 max-w-4xl mx-auto text-center">
        <h1 className="text-5xl sm:text-7xl font-display font-bold text-white mb-6">
          Get in <GradientText>Touch</GradientText>
        </h1>
        <p className="text-xl text-text-muted leading-relaxed">
          Questions? Partnership inquiries? We're here to help you scale your lending operations safely.
        </p>
      </section>

      {/* ─── Contact Form & Info ────────────────────── */}
      <section className="py-12 px-6 max-w-7xl mx-auto flex flex-col lg:flex-row gap-12">
        
        {/* Contact Form */}
        <div className="lg:w-2/3">
          <GlassCard className="p-8 sm:p-12">
            <h2 className="text-3xl font-display font-bold text-white mb-8">Send us a message</h2>
            <form className="space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-text-muted">Full Name</label>
                  <input type="text" className="w-full px-4 py-3 rounded-lg bg-bg border border-border text-white text-sm focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/50 transition-all" placeholder="Jane Doe" />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-text-muted">Work Email</label>
                  <input type="email" className="w-full px-4 py-3 rounded-lg bg-bg border border-border text-white text-sm focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/50 transition-all" placeholder="jane@company.com" />
                </div>
              </div>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-text-muted">Company Name</label>
                  <input type="text" className="w-full px-4 py-3 rounded-lg bg-bg border border-border text-white text-sm focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/50 transition-all" placeholder="Acme Finance" />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium text-text-muted">Subject</label>
                  <select className="w-full px-4 py-3 rounded-lg bg-bg border border-border text-white text-sm focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/50 transition-all appearance-none cursor-pointer">
                    <option>General Inquiry</option>
                    <option>Partnership</option>
                    <option>Support</option>
                    <option>Demo Request</option>
                  </select>
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium text-text-muted">Message</label>
                <textarea rows="5" className="w-full px-4 py-3 rounded-lg bg-bg border border-border text-white text-sm focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/50 transition-all resize-none" placeholder="How can we help you?"></textarea>
              </div>

              <Button type="button" variant="primary" className="w-full sm:w-auto px-10 py-4 text-lg mt-4">
                Send Message
              </Button>
            </form>
          </GlassCard>
        </div>

        {/* Contact Info Sidebar */}
        <div className="lg:w-1/3 space-y-8">
          <GlassCard className="p-8 border-t-4 border-t-primary">
            <h3 className="text-xl font-display font-bold text-white mb-6">Contact Information</h3>
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <span className="material-symbols-outlined text-primary mt-1">mail</span>
                <div>
                  <p className="text-sm font-medium text-white">Email Us</p>
                  <a href="mailto:contact@oakcred.com" className="text-sm text-text-muted hover:text-primary transition-colors">contact@oakcred.com</a>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <span className="material-symbols-outlined text-primary mt-1">schedule</span>
                <div>
                  <p className="text-sm font-medium text-white">Business Hours</p>
                  <p className="text-sm text-text-muted">Mon-Fri, 9AM-6PM IST</p>
                </div>
              </div>
            </div>
          </GlassCard>

          <GlassCard className="p-8">
            <h3 className="text-xl font-display font-bold text-white mb-6">Connect with Us</h3>
            <div className="flex gap-4">
              <a href="#" className="w-14 h-14 rounded-full bg-white/5 flex items-center justify-center text-text-muted hover:text-white hover:bg-[#0A66C2]/80 hover:shadow-[0_0_20px_rgba(10,102,194,0.4)] transition-all duration-300">
                <span className="material-symbols-outlined text-2xl">link</span>
              </a>
              <a href="#" className="w-14 h-14 rounded-full bg-white/5 flex items-center justify-center text-text-muted hover:text-white hover:bg-white/10 hover:shadow-[0_0_20px_rgba(255,255,255,0.1)] transition-all duration-300">
                <span className="material-symbols-outlined text-2xl">close</span>
              </a>
            </div>
          </GlassCard>
        </div>

      </section>

      {/* ─── FAQ Section ────────────────────────────── */}
      <section className="py-24 px-6 max-w-3xl mx-auto border-t border-border/50">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-5xl font-display font-bold text-white mb-4">Frequently Asked Questions</h2>
          <p className="text-text-muted text-lg">Can't find the answer you're looking for? Reach out to our team.</p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, i) => (
            <div 
              key={i} 
              className={`rounded-3xl transition-all duration-500 overflow-hidden backdrop-blur-md border border-white/5 ${
                openFaq === i ? 'bg-white/10 shadow-[0_4px_30px_rgba(245,158,11,0.05)]' : 'bg-white/[0.02] hover:bg-white/[0.04]'
              }`}
            >
              <button 
                onClick={() => setOpenFaq(openFaq === i ? -1 : i)}
                className="w-full flex items-center justify-between p-8 text-left focus:outline-none"
              >
                <span className={`text-lg font-medium pr-8 ${openFaq === i ? 'text-white' : 'text-text-muted'}`}>{faq.question}</span>
                <span className={`material-symbols-outlined text-primary transition-transform duration-500 rounded-full p-2 ${openFaq === i ? 'rotate-180 bg-primary/10' : ''}`}>
                  expand_more
                </span>
              </button>
              <div 
                className={`transition-all duration-500 ease-in-out ${
                  openFaq === i ? 'max-h-64 opacity-100 pb-8 px-8' : 'max-h-0 opacity-0 px-8'
                }`}
              >
                <p className="text-text-muted text-base leading-relaxed">{faq.answer}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

    </div>
  );
}
